graphql:
servlet:
enabled: true
mapping: /graphql
cors-enabled: true
cors:
allowed-origins: "*"
allowed-methods: GET, HEAD, POST
exception-handlers-enabled: true
context-setting: PER_REQUEST_WITH_INSTRUMENTATION
async-mode-enabled: true
max-query-depth: 50